Restrict shade version to avoid some monitoring check failure.
The latest test env installed with version 1.21.0, which cause some
check has error like below, and another test env with version 1.20.0 no
error.

 File
"/opt/openstack/base/local/lib/python2.7/site-packages/shade/_legacy_cli
ents.py", line 64, in neutron_client return
self._create_or_return_legacy_client('neutron', 'network')
AttributeError: 'OpenStackCloud' object has no attribute
'_create_or_return_legacy_client'